import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { dossiers, getDossier, revised } from '../../dossiers';
import { SiteHeader, SiteFooter, Direction } from '../../site-shell';
import { Emblem } from '../../identity';
import { Workflow } from '../../workflow';
import { ShareButton } from '../../share-button';

export function generateStaticParams(){return dossiers.map(d=>({slug:d.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const d=getDossier((await params).slug);return {title:d?`${d.title} — think.anas`:'Application not found',description:d?.summary,alternates:d?{canonical:`/applications/${d.slug}`}:undefined};}
export default async function ApplicationPage({params}:{params:Promise<{slug:string}>}){
 const d=getDossier((await params).slug);if(!d)notFound();
 const related=d.related.map(getDossier).filter((x):x is typeof d=>!!x);
 return <><SiteHeader/><main id="main" className="article-page"><header className={'article-hero '+d.color}><div><a className="back-link" href="/#applications">All AI applications</a><p className="eyebrow">{d.category}</p><h1>{d.title}</h1><p className="article-deck">{d.summary}</p><div className="article-meta"><span>Technical overview</span><span>Updated <time dateTime={revised}>20 September 2026</time></span></div></div><Emblem variant={d.emblem}/></header>
 <div className="article-layout"><aside className="article-toc"><p>In this analysis</p><nav aria-label="Article contents">{[['overview','Technical overview'],['workflow','Interactive workflow'],['example','Application example'],['evidence','Evidence & limitations'],['evaluation','Evaluation checklist'],['glossary','Key terms'],['sources','Sources']].map(([id,t])=><a key={id} href={'#'+id}>{t}</a>)}</nav><ShareButton/></aside>
 <article className="article-body"><section id="overview"><p className="eyebrow">Technical overview</p><h2>{d.question}</h2>{d.overview.map(p=><p key={p}>{p}</p>)}</section><section id="workflow"><h2>Follow the workflow.</h2><p>Select a stage to inspect the input, output and human checkpoint. This is a conceptual explanation, not a running clinical model.</p><Workflow dossier={d} compact/></section><section id="example"><p className="eyebrow">Illustrative application</p><h2>A concrete use case.</h2><p>{d.example}</p></section><section id="evidence"><p className="eyebrow">Evidence & limitations</p><h2>What the evidence tells us.</h2><p>{d.evidence} <a className="citation-link" href="#sources">See primary sources.</a></p><h3>Where to be careful</h3><ul className="reading-list">{d.limits.map(p=><li key={p}>{p}</li>)}</ul></section><section id="evaluation"><p className="eyebrow">Editorial evaluation checklist</p><h2>Questions before implementation.</h2><ul className="evaluation-list">{d.evaluation.map(p=><li key={p}>{p}</li>)}</ul><p className="small-note">These prompts support critical reading; they are not a clinical validation protocol.</p></section><section id="glossary"><h2>Key technical terms.</h2><dl className="glossary">{d.terms.map(([term,definition])=><div key={term}><dt>{term}</dt><dd>{definition}</dd></div>)}</dl></section><section id="sources"><h2>Sources & further reading.</h2><p>The selected sources support the evidence discussion. The workflow and evaluation questions are editorial explanations.</p><ol className="source-list">{d.sources.map(s=><li key={s.url}><span>{s.publisher} · {s.year}</span><a href={s.url} target="_blank" rel="noreferrer">{s.title}<Direction/></a></li>)}</ol><p className="small-note">Prepared with AI assistance. Educational synthesis, not peer review or medical advice. <a href="/methodology">Read our editorial method.</a></p><a className="text-link" href="https://www.instagram.com/think.anas/" target="_blank" rel="noreferrer">Suggest a correction on Instagram <Direction/></a></section></article></div>
 <section className="related-section"><div className="section-heading"><p className="eyebrow">Continue reading</p><h2>Connected applications.</h2></div><div className="related-grid">{related.map(r=><a className={'related-card '+r.color} href={'/applications/'+r.slug} key={r.slug}><Emblem variant={r.emblem}/><div><span className="eyebrow">{r.category}</span><h3>{r.title}</h3></div><Direction/></a>)}</div></section></main><SiteFooter/></>;
}
