export const tags=['All notes','In Practice','Under the Evidence','Human Judgment','Tools in Context','Learning Forward','From Idea to Care'];
export const notes=[
 ['A better answer starts with a better question.','Human Judgment','Field note','Before asking what AI can do, ask what a person actually needs.','Start with a situation, not a technology. Who is trying to make a decision? What information do they have? What would a useful answer change? These questions are a starting point for exploring a tool, not a claim about its clinical value.','Try writing the problem in one sentence without using the word AI. Then list what a useful outcome would look like for the person receiving care and the person providing it.'],
 ['Reading beyond the headline.','Under the Evidence','Reading guide','A small checklist for a more thoughtful reading of AI research.','What question was the study designed to answer? Who was included, and who was left out? What was the comparison? Look for how the authors describe limitations.','Keep a distinction between what the study measured and what you hope the technology could do. A helpful reading note records the question, the method, the reported result and the uncertainties separately.'],
 ['The tool is only part of the story.','Tools in Context','Open question','Where does a new tool fit into the work that already happens?','Imagine introducing a tool into a real working day. Who opens it? Who checks its output? What happens when it is unavailable or when someone disagrees with it?','Map the steps before and after the tool. Use that map to ask better questions about responsibility, effort and the experience of the people involved.'],
 ['Make room for the person.','In Practice','Reflection','An invitation to start with the experience of care.','Choose one moment in a care journey: preparing for an appointment, understanding a result or planning a follow-up. What is confusing? What would make the next step clearer?','This is an editorial exercise, not medical advice. Listening to the people involved is the next step before proposing a solution.'],
 ['Understand it. Then explain it simply.','Learning Forward','Resource','A three-part exercise for learning in public.','Write down an idea in plain language. Give an example of where it could be useful. Then explain what you still do not understand.','Keep a list of your sources beside the explanation. Revisit it when your understanding changes. The aim is clarity, not a performance of certainty.'],
 ['What is worth building next?','From Idea to Care','Working prompt','A useful starting point for a conversation with a builder.','Describe one specific problem and the person who experiences it. Ask how they handle it today, what they have already tried and what a meaningful improvement would be.','Before making a prototype, decide what you need to learn from it. A small experiment should help answer a question, rather than simply demonstrate a technology.']];
export const audiences=['I care for people.','I’m learning.','I build things.','I investigate questions.'];
export const audienceCopy=['Explore where technology meets the lived experience of care. Start with practical questions, human judgment and the work around the tool.','Build a vocabulary for AI and health, one useful question at a time. Find reading prompts and clear explanations you can return to.','Look beyond a compelling demo. Explore the problem, the workflow and the people who would use what you build.','Make space for methods, limitations and unanswered questions. Read past the headline and keep uncertainty visible.'];

