export type Source = { title: string; publisher: string; year: string; url: string };
export type Step = { title: string; input: string; process: string; output: string; checkpoint: string };
export type Dossier = { slug: string; title: string; category: string; color: string; emblem: number; summary: string; question: string; overview: string[]; example: string; evidence: string; limits: string[]; evaluation: string[]; terms: [string,string][]; sources: Source[]; steps: Step[]; related: string[] };
export const revised = '2026-09-20';
const who: Source = {title:'Guidance on large multi-modal models for health',publisher:'World Health Organization',year:'2024',url:'https://www.who.int/news/item/18-01-2024-who-releases-ai-ethics-and-governance-guidance-for-large-multi-modal-models'};
const devices: Source = {title:'Artificial Intelligence-Enabled Medical Devices',publisher:'US FDA',year:'Living resource',url:'https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices'};
export const dossiers: Dossier[] = [
 {
 slug:'clinical-decision-support',title:'Clinical Decision Support',category:'Predictive machine learning',color:'sky',emblem:1,
 summary:'Turn clinical data into risk estimates that a care team can interpret and act on.',question:'A prediction is useful only when there is a meaningful response.',
 overview:['A predictive model maps information available at a particular moment to an estimated outcome over a defined time window. In an early-warning workflow, that could mean combining observations from an electronic health record to estimate deterioration risk. The time window, eligible population and intended action are part of the problem definition.','Separate discrimination from calibration. A model may rank patients well while producing probabilities that do not match observed outcomes. Thresholds then determine which estimates become alerts. The resulting workload belongs in the evaluation alongside predictive performance.'],
 example:'Illustrative workflow: a hospital service receives a deterioration alert. A clinician checks the current observations and the patient’s condition before deciding whether escalation is appropriate. The alert is an input to assessment, not a diagnosis.',
 evidence:'The 2022 TREWS study examined associations between clinician interaction with a deployed sepsis alert and patient outcomes in a prospective, multisite cohort. Its observational design matters: an association does not, by itself, isolate the causal effect of an alert.',
 limits:['Missing observations and changes in how data are recorded can change model behaviour.','An alert without an available response can add workload rather than useful information.','Performance in one hospital or patient group does not establish performance elsewhere.'],
 evaluation:['Specify the outcome, prediction horizon and decision the output will inform.','Check calibration, sensitivity and alert volume in the intended population.','Evaluate the complete clinical workflow prospectively, including missed alerts and response times.'],
 terms:[['Calibration','Agreement between estimated probabilities and observed event frequencies.'],['Prediction horizon','The future interval over which an outcome is estimated.']],
 sources:[{title:'Prospective, multi-site study of patient outcomes after implementation of TREWS',publisher:'Nature Medicine · Adams et al.',year:'2022',url:'https://www.nature.com/articles/s41591-022-01894-0'},devices],
 steps:[{title:'Clinical data',input:'Observations and timestamps',process:'Check completeness, units and when each measurement became available.',output:'Time-aligned model inputs',checkpoint:'Exclude information recorded after the outcome.'},{title:'Risk estimation',input:'Validated inputs',process:'A fitted model calculates a risk estimate for a defined time window.',output:'Estimated risk',checkpoint:'Examine calibration in the intended population.'},{title:'Alert routing',input:'Risk estimate and threshold',process:'Apply a defined escalation rule and deliver the alert to a responsible team.',output:'An actionable notification',checkpoint:'Measure alert volume and identify who responds.'},{title:'Clinical assessment',input:'Notification and current condition',process:'The clinician reviews the patient, context and alternative explanations.',output:'Documented assessment and action',checkpoint:'The model does not replace bedside assessment.'}],related:['remote-patient-monitoring','medical-imaging-ai']
 },
 {
 slug:'workflow-automation',title:'Workflow Automation',category:'Automation & clinical operations',color:'lime-card',emblem:2,
 summary:'Reduce repeated administrative steps while keeping exceptions and responsibility visible.',question:'Measure the work removed — and the work moved elsewhere.',
 overview:['Automation coordinates tasks: receiving information, extracting fields, routing a request and recording its status. Some steps need a learned model; others are better expressed as explicit rules. The distinction helps a team understand which outputs can vary and which checks are deterministic.','Map the existing process before changing it. A useful map includes the person who receives each output, the system of record and the route for exceptions. A fast draft is not automatically a faster workflow if reviewing and correcting it takes longer.'],
 example:'Illustrative workflow: a referral arrives, a system extracts the requested service and identifies missing fields, then a coordinator confirms the destination. An incomplete or ambiguous referral returns to a review queue instead of being silently routed.',
 evidence:'A randomised trial of ambient AI scribes included 238 physicians at one academic institution and English-only encounters. This is a concrete example of studying an automation workflow; that setting limits how broadly its findings can be transferred. It does not validate referral routing or administrative automation as a whole.',
 limits:['A model can confidently extract the wrong field from an unusual document.','Integration failures may duplicate tasks or leave records out of sync.','Automation can shift checking work onto staff who were not included in the design.'],
 evaluation:['Measure end-to-end handling time, including corrections and exceptions.','Define a rollback path and an audit trail for each automated action.','Test unusual inputs, failed integrations and handovers between teams.'],
 terms:[['Human-in-the-loop','A defined point where a person reviews or authorises an output.'],['Exception handling','The route for inputs that cannot be processed reliably by the normal workflow.']],
 sources:[{title:'Ambient AI Scribes in Clinical Practice: A Randomized Trial',publisher:'Primary trial · PubMed Central',year:'2025',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC12768499/'},who],
 steps:[{title:'Receive',input:'Referral or administrative request',process:'Identify the document and verify the permitted processing route.',output:'A tracked request',checkpoint:'Use a traceable identifier and an appropriate access policy.'},{title:'Extract',input:'Document content',process:'Suggest structured fields and flag missing information.',output:'Draft structured record',checkpoint:'Uncertain fields stay visible.'},{title:'Review',input:'Draft fields and original document',process:'A coordinator checks discrepancies and confirms the destination.',output:'Authorised routing decision',checkpoint:'Review precedes the consequential action.'},{title:'Record',input:'Confirmed decision',process:'Update the system of record and report failures.',output:'Completed task or exception queue',checkpoint:'Do not silently discard failed updates.'}],related:['clinical-nlp-llms','clinical-decision-support']
 },
 {
 slug:'clinical-nlp-llms',title:'Clinical NLP & LLMs',category:'Natural language processing',color:'coral',emblem:3,
 summary:'Extract, retrieve and summarise clinical language without losing its context or provenance.',question:'A fluent sentence is not evidence that a clinical statement is correct.',
 overview:['Clinical natural language processing converts text into useful representations: entities, relationships, document categories or retrieved passages. Large language models can also generate text. These are different tasks, and they need different evaluation criteria.','In a retrieval-augmented workflow, a system first selects passages from an authorised collection, then uses those passages as context for a generated answer. Retrieval helps expose the source material, but neither retrieval nor citations guarantee that the answer faithfully reflects it.'],
 example:'Illustrative workflow: an ambient documentation system produces a draft clinical note from a conversation. Before saving, the clinician compares it with the encounter, checking speaker attribution, negation, chronology and any statement not supported by the conversation.',
 evidence:'WHO’s 2024 guidance describes health applications of large multimodal models and flags inaccurate, biased or incomplete outputs and automation bias. It is governance guidance, not a clinical effectiveness trial. A separate primary study listed below evaluates the quality of AI-generated clinical notes.',
 limits:['Negation and temporality matter: a historical condition is not necessarily a current diagnosis.','Generated text may omit details or add unsupported statements.','Retrieval can select outdated, irrelevant or unauthorised content.'],
 evaluation:['Assess factual consistency and clinically important omissions, not fluency alone.','Keep the source passage or encounter available during review.','Test performance across the languages and document types actually used.'],
 terms:[['RAG','Retrieval-augmented generation: generating an answer using retrieved source material.'],['Entity extraction','Identifying mentions such as medications, symptoms or dates in text.']],
 sources:[who,{title:'Assessing the quality of AI-generated clinical notes',publisher:'Primary study · PubMed',year:'2025',url:'https://pubmed.ncbi.nlm.nih.gov/41199808/'}],
 steps:[{title:'Source material',input:'Authorised text or conversation',process:'Capture the content with its context and access constraints.',output:'Traceable source material',checkpoint:'Check permission, scope and speaker attribution.'},{title:'Language model',input:'Source and task instructions',process:'Extract information or generate a structured draft.',output:'Proposed clinical text',checkpoint:'A plausible completion can still be unsupported.'},{title:'Source check',input:'Draft alongside its source',process:'Compare statements, negations, dates and missing details.',output:'Identified corrections',checkpoint:'Check omissions as well as additions.'},{title:'Human validation',input:'Reviewed draft',process:'A clinician corrects and approves the note before saving.',output:'An accountable record',checkpoint:'Approval is a real review step, not a decorative button.'}],related:['workflow-automation','medical-imaging-ai']
 },
 {
 slug:'medical-imaging-ai',title:'Medical Imaging AI',category:'Computer vision',color:'violet',emblem:4,
 summary:'Analyse medical images for defined tasks such as detection, segmentation or prioritisation.',question:'An image-level result must be evaluated in the clinical workflow around it.',
 overview:['Detection identifies a candidate finding; segmentation outlines a region; classification assigns a category. Although all may use computer vision, their outputs and failure modes are different. A result should be interpreted within the task and imaging protocol for which it was evaluated.','A clinical imaging workflow includes acquisition, quality checks, model processing, interpretation and reporting. Scanner characteristics, patient positioning and acquisition protocols can change the input distribution. An attractive visual overlay does not establish diagnostic reliability.'],
 example:'Illustrative workflow: a triage system flags an examination for earlier specialist review. The radiologist still interprets the full examination and the clinical context. Prioritising a study and making a diagnosis are separate actions.',
 evidence:'The FDA maintains a list of AI-enabled medical devices with links to individual authorisation records, including radiology applications. The list is not exhaustive. An entry is a starting point for checking intended use and available evidence, rather than a ranking or a blanket endorsement of a technology.',
 limits:['Performance can change across scanners, protocols and institutions.','An overlay may encourage attention to the marked region while distracting from other findings.','Retrospective image accuracy does not alone demonstrate better patient outcomes.'],
 evaluation:['Check the exact task, intended use and acquisition requirements.','Evaluate false negatives, false positives and subgroup performance.','Study reader interaction, turnaround time and downstream consequences.'],
 terms:[['Segmentation','Assigning pixels or voxels to an anatomical structure or region.'],['Distribution shift','A difference between development data and the inputs encountered in use.']],
 sources:[devices],
 steps:[{title:'Image acquisition',input:'Medical examination',process:'Acquire images using an appropriate protocol.',output:'Image series and metadata',checkpoint:'Verify input quality and intended modality.'},{title:'Model analysis',input:'Compatible image series',process:'Perform the defined detection, segmentation or classification task.',output:'Task-specific model result',checkpoint:'Do not assume the model detects every type of finding.'},{title:'Specialist review',input:'Full examination and model result',process:'Interpret the images in context and review disagreement.',output:'Clinical interpretation',checkpoint:'Review the complete study, not only the overlay.'},{title:'Report',input:'Specialist interpretation',process:'Document findings and the appropriate next step.',output:'An accountable report',checkpoint:'Track discrepancies and workflow impact.'}],related:['clinical-decision-support','precision-medicine']
 },
 {
 slug:'precision-medicine',title:'Precision Medicine',category:'Genomics & multimodal learning',color:'gold',emblem:5,
 summary:'Combine biological and clinical information to investigate differences between patients.',question:'A molecular prediction is one piece of evidence, not a treatment decision.',
 overview:['Precision medicine asks how differences in biology, environment and clinical history can inform care. AI methods can help prioritise hypotheses or combine representations of several data types. The model’s target might be a molecular effect, a disease-associated pattern or an outcome; those targets are not interchangeable.','Combining modalities creates additional questions. Were all samples collected at comparable times? Which groups are represented? What happens when one modality is missing? A useful evaluation examines the value of each input as well as the combined model.'],
 example:'Illustrative workflow: a researcher uses a variant-effect prediction to prioritise variants for further investigation. A genetics specialist considers the patient’s phenotype, family information and other evidence. The computational prediction does not independently establish a clinical diagnosis.',
 evidence:'The AlphaMissense research combines structural context and evolutionary conservation to predict missense variant pathogenicity and reports benchmark evaluations. These are predictions about variant effects, not evidence that a model independently selects a treatment or diagnoses a patient.',
 limits:['A benchmark result does not establish clinical utility in a new population.','Underrepresented ancestries and missing modalities complicate interpretation.','Molecular association, disease causation and treatment response are distinct questions.'],
 evaluation:['State precisely which biological or clinical endpoint is predicted.','Keep independent evidence separate from model-derived evidence.','Assess generalisation and the consequences of uncertain classifications.'],
 terms:[['Multimodal learning','Learning from more than one type of input, such as sequence, image and clinical data.'],['Missense variant','A DNA change that results in an amino-acid substitution in a protein.']],
 sources:[{title:'Accurate proteome-wide missense variant effect prediction with AlphaMissense',publisher:'Google DeepMind · research publication',year:'2023',url:'https://deepmind.google/research/publications/21083/'}],
 steps:[{title:'Biological inputs',input:'Sequence and clinical context',process:'Check data quality, provenance and what information is missing.',output:'Defined evidence set',checkpoint:'Representation and consent belong in the data review.'},{title:'Computational prediction',input:'Eligible biological data',process:'Estimate a specific molecular effect or relationship.',output:'Score or prioritised hypotheses',checkpoint:'Name the predicted endpoint precisely.'},{title:'Evidence integration',input:'Prediction plus independent findings',process:'Compare model output with other biological and clinical evidence.',output:'A contextual interpretation',checkpoint:'Do not count correlated model outputs as independent proof.'},{title:'Specialist assessment',input:'Integrated evidence',process:'Determine what further investigation is appropriate.',output:'A documented next step',checkpoint:'A model score is not a standalone treatment recommendation.'}],related:['medical-imaging-ai','clinical-nlp-llms']
 },
 {
 slug:'remote-patient-monitoring',title:'Remote Patient Monitoring',category:'Time-series & physiological signals',color:'ink-card',emblem:6,
 summary:'Interpret longitudinal signals outside the clinic and connect them to a response pathway.',question:'Who receives the signal, and what can they actually do next?',
 overview:['Remote monitoring links measurement, signal processing, interpretation and follow-up. A wearable or home sensor may produce frequent observations, but more measurements do not automatically mean more useful information. Signal quality and missingness are part of the system.','Algorithms may identify unusual patterns or summarise changes over time. The care pathway still needs to define recipients, response windows and confirmation steps. Evaluating the detector without evaluating that pathway leaves much of the product unexamined.'],
 example:'Illustrative workflow: a device identifies an irregular rhythm pattern and prompts confirmatory assessment. The recipient needs understandable instructions and an available route to follow-up. A notification should not be presented as a definitive diagnosis.',
 evidence:'The Apple Heart Study was a prospective, single-group study of smartwatch irregular-pulse notifications with follow-up ECG assessment. It demonstrates a detection-and-confirmation pathway. Its design does not establish that wearable screening reduces stroke, nor does it validate every monitoring algorithm.',
 limits:['Motion artefacts, inconsistent wear and connectivity gaps can affect measurements.','False alerts can create anxiety and additional clinical work.','Access to a device does not guarantee access to follow-up care.'],
 evaluation:['Assess signal quality, adherence and missing-data patterns.','Measure alert burden and completion of confirmatory assessment.','Evaluate outcomes separately from detection performance.'],
 terms:[['Time series','Measurements indexed by time, where ordering and intervals matter.'],['Positive predictive value','The proportion of positive results that correspond to the target condition in the evaluated setting.']],
 sources:[{title:'Large-Scale Assessment of a Smartwatch to Identify Atrial Fibrillation',publisher:'New England Journal of Medicine · Perez et al.',year:'2019',url:'https://www.nejm.org/doi/full/10.1056/NEJMoa1901183'}],
 steps:[{title:'Measurement',input:'Wearable or home-sensor signal',process:'Capture measurements and identify artefacts or gaps.',output:'Quality-checked time series',checkpoint:'Missing data must remain visible.'},{title:'Signal analysis',input:'Time series',process:'Identify patterns according to a defined algorithm.',output:'Candidate event or trend',checkpoint:'A signal pattern is not a confirmed diagnosis.'},{title:'Notification',input:'Candidate event',process:'Route understandable information to the intended recipient.',output:'A follow-up request',checkpoint:'Specify who responds and in what time frame.'},{title:'Confirmation',input:'Notification and additional assessment',process:'A care team reviews the signal and obtains appropriate confirmation.',output:'Documented follow-up',checkpoint:'Measure whether the pathway was completed.'}],related:['clinical-decision-support','workflow-automation']
 }
];
export function getDossier(slug: string) { return dossiers.find(d => d.slug === slug); }
