import { SiteHeader, SiteFooter, Direction } from './site-shell';
import { Emblem, LivingSculpture } from './identity';
import { dossiers } from './dossiers';
import { WorkflowExplorer } from './workflow';

export default function Home(){return <><SiteHeader/><main id="main">
 <section className="home-hero"><div className="hero-copy"><p className="eyebrow">Independent thinking · AI & healthcare</p><h1>Stay human.<br/><em>Think further.</em></h1><p className="hero-description">Understand clinical AI.<br/>Examine the evidence.<br/>See where human judgment matters.</p><div className="hero-actions"><a className="primary-action" href="#applications">Explore AI applications <Direction/></a><a className="quiet-action" href="#workflows">Try a workflow</a></div></div><div className="hero-sculpture"><LivingSculpture/></div><div className="hero-note"><span>Methods, applications & limitations.</span><a href="/methodology">Our editorial method <Direction/></a></div></section>
 <section id="applications" className="applications-section"><div className="section-heading"><div><p className="eyebrow">AI Applications</p><h2>Understand the systems.<br/><em>Consider the consequences.</em></h2></div><p>Six technical guides to the applications shaping healthcare. Each connects a method to its workflow, evidence and limits.</p></div><div className="application-grid">{dossiers.map(d=><a className={'application-card '+d.color} key={d.slug} href={'/applications/'+d.slug} aria-label={'Read '+d.title}><div className="card-art"><Emblem variant={d.emblem}/><span className="card-orbit" aria-hidden="true"/></div><div className="card-content"><p className="eyebrow">{d.category}</p><h3>{d.title}</h3><p>{d.summary}</p><span className="card-action">Read the analysis <Direction/></span></div></a>)}</div></section>
 <section className="featured-analysis"><div className="featured-copy"><p className="eyebrow">Featured analysis · Clinical NLP & LLMs</p><h2>From spoken words<br/>to a clinical record.<br/><em>What gets lost?</em></h2><p>Transcription, generation, source verification and clinician review. Explore how a documentation workflow works — and where it can fail.</p><a className="primary-action" href="/applications/clinical-nlp-llms">Read the full analysis <Direction/></a></div><div className="featured-diagram" aria-label="Illustrative documentation workflow"><div className="transcript-sheet"><span>Source conversation</span><div className="audio-bars" aria-hidden="true">{[22,35,17,49,68,31,54,78,40,26,62,42,19,54,31,69,46,28,38].map((h,i)=><i style={{height:h+'%'}} key={i}/>)}</div><p>Context. Speaker. Meaning.</p></div><div className="draft-sheet"><Emblem variant={3}/><span>Generated draft</span><div className="document-lines" aria-hidden="true"><i/><i/><i/><i/></div><strong>Human review required</strong></div><span className="diagram-caption">Conceptual illustration · no patient data</span></div></section>
 <section id="workflows" className="workflows-section"><div className="section-heading"><div><p className="eyebrow">Interactive workflows</p><h2>Follow the data.<br/><em>Find the decision.</em></h2></div><p>Explore what enters a system, what comes out and where a person needs to review it.</p></div><WorkflowExplorer/></section>
 <section className="editorial-section"><div><p className="eyebrow">How to read this collection</p><h2>Evidence deserves<br/><em>its own space.</em></h2><a className="text-link" href="/methodology">Read the editorial method <Direction/></a></div><div className="editorial-principles"><article><h3>Trace the claim.</h3><p>Open the original source. Check what was measured and in which setting.</p></article><article><h3>Keep uncertainty visible.</h3><p>Read limitations alongside applications. A benchmark is not a clinical outcome.</p></article><article><h3>Examine the whole workflow.</h3><p>Look at the people, handovers and decisions around the model.</p></article></div></section>
 <section id="about" className="about-section"><div className="portrait-frame"><img src="/anas.png" alt="Portrait of Anas, creator of think.anas" width="1254" height="1254" loading="lazy"/><span className="portrait-caption">Anas · @think.anas</span></div><div className="about-text"><p className="eyebrow">About Anas</p><h2>Curiosity started this.<br/><em>Questions keep it moving.</em></h2><p>I’m Anas, the person behind think.anas. This is my space to explore artificial intelligence in healthcare, connect technical ideas to real applications and learn in public.</p><p>The questions I keep coming back to: what does a system actually do, what supports its claims, and how does it change the experience of care?</p><div className="personal-note">“What would change my mind?”<span>A question worth keeping close.</span></div><a className="text-link" href="https://www.instagram.com/think.anas/" target="_blank" rel="noreferrer">Connect with @think.anas <Direction/></a></div></section>
 <section id="contact" className="contact-section"><div><p className="eyebrow">Contact & collaboration</p><h2>A useful question.<br/><em>A good place to start.</em></h2><p>Discuss a project, share a paper or suggest a correction. Reach Anas directly on Instagram.</p></div><a className="contact-destination" href="https://www.instagram.com/think.anas/" target="_blank" rel="noreferrer"><span>Instagram</span><strong>@think.anas</strong><Direction/><span className="contact-hint">Open profile to send a message</span></a></section>
 </main><SiteFooter/></>;}
