"use client";
import { useEffect, useState } from 'react';
import { FluentProvider, webDarkTheme, Button, Input, Field, Textarea, Select, Dialog, DialogSurface, DialogBody, DialogTitle, DialogContent, DialogActions } from '@fluentui/react-components';
import { notes, audiences, audienceCopy } from './content';
const theme = { ...webDarkTheme, fontFamilyBase: 'Arial, sans-serif', colorBrandBackground: '#e2ff54', colorBrandBackgroundHover: '#cbe83d', colorBrandBackgroundPressed: '#c0dc37', colorNeutralForegroundOnBrand: '#101b2a', colorBrandForeground1: '#e2ff54', colorCompoundBrandStroke: '#e2ff54', borderRadiusMedium: '2px' };
function Symbol({ className = '' }: { className?: string }) { return <img className={'brand-symbol ' + className} src="/brand-symbol.png" alt="" />; }
function Wordmark() { return <span className="wordmark"><Symbol /><span>think<span className="wordmark-dot">.</span>anas</span></span>; }
const fieldMap = [
 { id: '01', name: 'Clinical Intelligence', tag: 'PREDICTIVE AI', icon: 'pulse', color: 'sky', description: 'From risk signals to decision support: making complex clinical data easier to read, question and act on.', examples: 'Triage · deterioration risk · decision support', note: 0 },
 { id: '02', name: 'Care Automation', tag: 'WORKFLOW AI', icon: 'loop', color: 'lime-card', description: 'Where repetitive administration can become quieter, so clinicians can spend more time on people and the work that matters.', examples: 'Ambient documentation · coding · care coordination', note: 2 },
 { id: '03', name: 'Language & Records', tag: 'NLP + LLMs', icon: 'quote', color: 'coral', description: 'How machines read, structure and generate health language — and why clarity, provenance and oversight have to stay visible.', examples: 'Clinical notes · retrieval · patient communication', note: 1 },
 { id: '04', name: 'Medical Vision', tag: 'COMPUTER VISION', icon: 'eye', color: 'violet', description: 'Reading images, slides and video with AI. The interesting question is not only what a model sees, but how care changes around it.', examples: 'Radiology · pathology · ophthalmology', note: 3 },
 { id: '05', name: 'Precision Biology', tag: 'MULTIMODAL AI', icon: 'helix', color: 'gold', description: 'Connecting genomics, biomarkers, images and records to move from population averages toward more specific questions.', examples: 'Genomics · drug discovery · tailored treatment', note: 4 },
 { id: '06', name: 'Connected Care', tag: 'SENSING + SIGNALS', icon: 'wave', color: 'ink-card', description: 'What changes when health signals continue beyond the clinic — and when monitoring becomes part of daily life?', examples: 'Wearables · remote monitoring · population health', note: 5 },
];
function FieldIcon({ kind }: { kind: string }) { const common = { fill: 'none', stroke: 'currentColor', strokeWidth: 2.2, strokeLinecap: 'round' as const, strokeLinejoin: 'round' as const }; return <svg className="field-icon" viewBox="0 0 64 64" aria-hidden="true">{kind === 'pulse' && <><path {...common} d="M6 36h11l7-20 11 35 7-15h16"/><circle cx="32" cy="32" r="27" {...common}/></>}{kind === 'loop' && <><path {...common} d="M15 25a19 19 0 0 1 33-5l4 6M49 39a19 19 0 0 1-33 5l-4-6"/><path {...common} d="m52 17 1 9-9-1M12 47l-1-9 9 1"/></>}{kind === 'quote' && <><path {...common} d="M13 21h15v14c0 9-5 14-14 16M37 21h15v14c0 9-5 14-14 16"/><path {...common} d="M21 34h7M45 34h7"/></>}{kind === 'eye' && <><path {...common} d="M5 32s10-15 27-15 27 15 27 15-10 15-27 15S5 32 5 32Z"/><circle cx="32" cy="32" r="8" {...common}/></>}{kind === 'helix' && <><path {...common} d="M18 10c30 9 0 35 28 44M46 10C16 19 46 45 18 54M21 18h22M17 32h30M21 46h22"/></>}{kind === 'wave' && <><path {...common} d="M7 36c7 0 7-16 14-16s7 24 14 24 7-32 14-32 7 20 8 20"/><path {...common} d="M7 52h50"/></>}</svg> }
export default function Home() {
 const [audience, setAudience] = useState(0); const [article, setArticle] = useState<number | null>(null); const [contact, setContact] = useState(false); const [menu, setMenu] = useState(false); const [feedback, setFeedback] = useState(''); const [scrolled, setScrolled] = useState(false);
 useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 30); onScroll(); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll); }, []);
 function explore(_field?: string) { document.getElementById('explore')?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' }); }
 return <FluentProvider theme={theme} className="site"><a className="skip" href="#main">Skip to content</a>
 <header className={'masthead ' + (scrolled ? 'compact' : '')}><a href="#" aria-label="think.anas home"><Wordmark /></a><nav className={menu ? 'navigation expanded' : 'navigation'} aria-label="Main navigation"><span className="nav-orbit" aria-hidden="true">✳</span><a href="#explore" onClick={() => setMenu(false)}><sup>01</sup>FIELDS</a><a href="#perspectives" onClick={() => setMenu(false)}><sup>02</sup>PEOPLE</a><a href="#about" onClick={() => setMenu(false)}><sup>03</sup>ANAS</a></nav><button className="nav-contact" aria-label="Start a conversation" onClick={() => setContact(true)}><span className="contact-label">OPEN A CONVERSATION</span><span>↗</span></button><Button className="menu-button" aria-expanded={menu} aria-label="Toggle navigation" onClick={() => setMenu(!menu)}>{menu ? '×' : '☰'}</Button></header>
 <main id="main"><section className="hero"><div className="hero-topline"><p className="micro">INDEPENDENT THINKING AT THE INTERSECTION OF AI & HEALTH</p><span className="micro hero-edition">AN OPEN FIELD OF EXPLORATION</span></div><div className="hero-composition"><div className="hero-type"><h1>Stay human.<br/><span>Think further.</span></h1><div className="hero-intro"><span className="tiny-cross" aria-hidden="true">+</span><p>Artificial intelligence is changing the conversation.<br className="desktop-break"/> I’m Anas. Let’s ask what it means for people.</p></div><a className="button-lime" href="#explore">Step into the ideas <span>↗</span></a></div><figure className="hero-art"><img src="/human-intelligence.png" alt="An ultramarine iris suspended inside a sculptural glass lens, an artistic meeting of living form and precision"/><figcaption><span>FIG. 01</span> THE LIVING / THE LEARNING</figcaption></figure><div className="margin-note">A little less noise.<br/>A lot more curiosity.</div></div><div className="hero-bottom"><span>THINK.ANAS — A PERSONAL EXPLORATION</span><a href="#manifesto">Scroll to discover <span>↓</span></a></div></section>
 <div className="ribbon" aria-label="Human questions, artificial intelligence, real perspective"><span>HUMAN QUESTIONS</span><span aria-hidden="true">✳</span><span>ARTIFICIAL INTELLIGENCE</span><span aria-hidden="true">✳</span><span>REAL PERSPECTIVE</span><span aria-hidden="true">✳</span></div>
 <section id="manifesto" className="manifesto light-section"><div className="section-label"><span className="micro">THE STARTING POINT</span><span className="micro">[ NOT ANOTHER TECH MONOLOGUE ]</span></div><div className="manifesto-grid"><span className="large-asterisk" aria-hidden="true">✳</span><div><h2>More than what AI <i>can</i> do.<br/>What should it <i>mean</i> for us?</h2><div className="manifesto-bottom"><p>Health is human. Technology is a tool. This is a space to explore the messy, fascinating territory in between — with curiosity, context and an open mind.</p><a className="underlined" href="#about">The person behind the questions <span>↗</span></a></div></div></div></section>
 <section id="explore" className="index-section light-section"><div className="section-label"><span className="micro">01 / THE INDEX</span><span className="micro">COLLECTED THOUGHTS. OPEN QUESTIONS.</span></div><div className="index-heading"><h2>Follow your<br/><i>curiosity.</i></h2><div><p>Notes to pause on.<br/>Questions to take with you.</p><span className="sample-label">EDITORIAL SAMPLE COLLECTION</span></div></div><div className="featured-grid"><button className="featured-note" onClick={() => setArticle(0)}><span className="micro">HUMAN JUDGMENT / FIELD NOTE</span><span className="featured-punctuation" aria-hidden="true">?</span><h3>Better questions.<br/><i>More human answers.</i></h3><span className="featured-foot">Before asking what AI can do, ask what a person actually needs.<span className="round-arrow">↗</span></span></button><div className="side-notes"><button onClick={() => setArticle(1)}><span className="micro">UNDER THE EVIDENCE / READING GUIDE</span><div><h3>The headline is<br/>only the beginning.</h3><span>↗</span></div><p>A checklist for reading beyond the promise.</p></button><button onClick={() => setArticle(2)}><span className="micro">TOOLS IN CONTEXT / OPEN QUESTION</span><div><h3>A tool doesn’t work<br/>in a vacuum.</h3><span>↗</span></div><p>Look at the world around the technology.</p></button></div></div>
 <div className="field-map-intro"><div><span className="micro">SIX MAJOR FIELDS / ONE HUMAN QUESTION</span><h3>The map of<br/><i>AI × Health.</i></h3></div><p>Move across a field to open it. Each one is a different way AI is already meeting health — with its own promise, limits and human stakes.</p></div><div className="field-map" aria-label="Six major artificial intelligence and health fields">{fieldMap.map(field => <button className={'field-card ' + field.color} key={field.id} onClick={() => setArticle(field.note)}><span className="field-index">{field.id}</span><div className="field-mark"><FieldIcon kind={field.icon}/></div><div className="field-base"><span className="field-tag">{field.tag}</span><h3>{field.name}</h3></div><div className="field-reveal"><p>{field.description}</p><span>{field.examples}</span><b>OPEN FIELD ↗</b></div></button>)}</div><p className="collection-caption">This is an editorial map, not a clinical taxonomy. It is a useful way to start exploring the terrain.</p></section>
 <section id="perspectives" className="perspectives dark-section"><div className="section-label"><span className="micro">02 / YOUR PERSPECTIVE</span><span className="micro">THERE IS MORE THAN ONE WAY IN</span></div><div className="perspective-heading"><h2>Different minds.<br/><span>Same frontier.</span></h2><p>You don’t need the same background.<br/>Just a reason to be curious.</p></div><div className="perspective-grid"><div className="perspective-tabs" role="group" aria-label="Choose your perspective">{audiences.map((a,i) => <button key={a} aria-pressed={audience === i} onClick={() => setAudience(i)} className={audience === i ? 'selected' : ''}><span className="micro">0{i+1}</span>{a}<span>↗</span></button>)}</div><div className="perspective-panel" aria-live="polite"><span className="micro">YOUR STARTING POINT / 0{audience+1}</span><h3>{['Care comes first.','Keep asking why.','Make something useful.','Stay with the question.'][audience]}</h3><p>{audienceCopy[audience]}</p><button className="underlined" onClick={() => explore(['In Practice','Learning Forward','From Idea to Care','Under the Evidence'][audience])}>Find your next read <span>↗</span></button></div></div></section>
 <section id="about" className="about-section light-section"><div className="section-label"><span className="micro">03 / THE HUMAN</span><span className="micro">YES, THERE’S A PERSON BEHIND THIS.</span></div><div className="about-grid"><div className="portrait-composition"><figure><img src="/anas.png" alt="Anas, the person behind think.anas"/><figcaption>ANAS <span>ALWAYS A WORK IN PROGRESS.</span></figcaption></figure><span className="portrait-sticker">Human.<br/>Still learning.</span></div><div className="about-copy"><p className="micro">CREATOR OF @THINK.ANAS</p><h2>Hi, I’m Anas.<br/><i>Curiosity led me here.</i></h2><p>I’m exploring what happens when artificial intelligence meets human health. The possibilities, the unanswered questions, and the people at the centre of it all.</p><p>think.anas is where I connect the dots. A personal space for learning in public, thinking a little deeper and finding people to explore with.</p><a className="underlined" href="https://www.instagram.com/think.anas/" target="_blank" rel="noreferrer">Meet me on Instagram <span>↗</span></a></div></div><div className="principles"><span className="micro">THREE THINGS I COME BACK TO</span>{[['01','Ask something useful.'],['02','Follow the evidence.'],['03','Remember the person.']].map(([n,t]) => <div key={n}><span className="micro">{n}</span><h3>{t}</h3></div>)}</div></section>
 <section className="collaboration-section"><div className="section-label"><span className="micro">04 / THE NEXT CONVERSATION</span><span className="micro">OPEN TO IDEAS. OPEN TO PEOPLE.</span></div><div className="collaboration-heading"><h2>Good ideas<br/>need <i>company.</i></h2><button className="giant-arrow" aria-label="Bring an idea" onClick={() => setContact(true)}>↗</button></div><div className="collaboration-bottom"><p>A shared question. A useful resource.<br/>An experiment worth trying.<br/>Let’s see where a conversation takes us.</p><div className="collaboration-types"><span>EXPLORE</span><span>EXPLAIN</span><span>BUILD</span><span>BRING PEOPLE TOGETHER</span></div><button className="button-ink" onClick={() => setContact(true)}>Bring an idea <span>↗</span></button></div></section>
 <footer><div className="footer-top"><a href="#" aria-label="Back to top"><Wordmark /></a><p>Stay human. Think further.</p><a href="https://www.instagram.com/think.anas/" target="_blank" rel="noreferrer">Instagram ↗</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} THINK.ANAS</span><span>AI × HEALTH × HUMAN CURIOSITY</span><a href="#">BACK TO TOP ↑</a></div></footer></main>
 <Dialog open={article !== null} onOpenChange={(_,d) => !d.open && setArticle(null)}><DialogSurface className="reading-dialog"><DialogBody><DialogTitle>{article !== null ? notes[article][0] : ''}</DialogTitle><DialogContent>{article !== null && <><p className="dialog-meta">{notes[article][1]} / {notes[article][2]} / Editorial sample</p>{notes[article].slice(4).map(p => <p className="article-p" key={p}>{p}</p>)}</>}</DialogContent><DialogActions><Button appearance="primary" onClick={() => setArticle(null)}>Back to the index</Button></DialogActions></DialogBody></DialogSurface></Dialog>
 <Dialog open={contact} onOpenChange={(_,d) => { setContact(d.open); setFeedback(''); }}><DialogSurface className="contact-dialog"><DialogBody><DialogTitle>Every good idea starts somewhere.</DialogTitle><DialogContent><p>Prepare a short introduction, then share it with @think.anas on Instagram. This form creates a download; it does not send a message.</p><form id="idea-form" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); const text = Array.from(data.entries()).map(([k,v]) => `${k}: ${v}`).join('\n\n'); const url = URL.createObjectURL(new Blob([text], { type: 'text/plain' })); const a = document.createElement('a'); a.href = url; a.download = 'an-idea-for-think-anas.txt'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setFeedback('Your introduction is ready to download. Share it with @think.anas to start the conversation.'); }}><div className="form-pair"><Field label="Your name" required><Input name="Name" required /></Field><Field label="Email or Instagram" required><Input name="Contact" required /></Field></div><Field label="What brings you here?"><Select name="Collaboration"><option>A question to explore</option><option>A resource to create</option><option>An experiment to build</option><option>A podcast or workshop</option><option>Something unexpected</option></Select></Field><Field label="Tell me the idea" required><Textarea name="Idea" required rows={4} /></Field><Field label="Timing, if you have it"><Input name="Timing" /></Field></form><p role="status">{feedback}</p><a className="underlined" href="https://www.instagram.com/think.anas/" target="_blank" rel="noreferrer">Open @think.anas ↗</a></DialogContent><DialogActions><Button onClick={() => setContact(false)}>Close</Button><Button appearance="primary" form="idea-form" type="submit">Download introduction ↗</Button></DialogActions></DialogBody></DialogSurface></Dialog>
 </FluentProvider>;
}
