"use client";
import { useEffect, useState } from 'react';
import { FluentProvider, webDarkTheme, Button, Input, Field, Textarea, Select, Dialog, DialogSurface, DialogBody, DialogTitle, DialogContent, DialogActions } from '@fluentui/react-components';

import { Emblem, TMark, LivingSculpture } from './identity';
const theme = { ...webDarkTheme, fontFamilyBase: 'Arial, sans-serif', colorBrandBackground: '#e2ff54', colorBrandBackgroundHover: '#cbe83d', colorBrandBackgroundPressed: '#c0dc37', colorNeutralForegroundOnBrand: '#101b2a', colorBrandForeground1: '#e2ff54', colorCompoundBrandStroke: '#e2ff54', borderRadiusMedium: '2px' };
function Symbol({ className = '' }: { className?: string }) { return <TMark className={'brand-symbol ' + className}/>; }
function Wordmark() { return <span className="wordmark"><Symbol /><span>think<span className="wordmark-dot">.</span>anas</span></span>; }
function VectorMark({ className = '' }: { className?: string }) { return <span className={'vector-mark ' + className} aria-hidden="true"><svg viewBox="0 0 42 42"><path d="M7 29 29 7M15 7h14v14M7 18v11h11" fill="none" stroke="currentColor" strokeWidth="2.7" strokeLinecap="square"/><circle cx="33" cy="33" r="4.25" fill="currentColor"/></svg></span>; }
const fieldMap = [
 { id: '01', name: 'Clinical Decision Support', tag: 'PREDICTIVE AI', icon: 'pulse', color: 'sky', description: 'From risk signals to decision support: making complex clinical data easier to read, question and act on.', examples: 'Triage · deterioration risk · decision support', note: 0 },
 { id: '02', name: 'Workflow Automation', tag: 'WORKFLOW AI', icon: 'loop', color: 'lime-card', description: 'Where repetitive administration can become quieter, so clinicians can spend more time on people and the work that matters.', examples: 'Ambient documentation · coding · care coordination', note: 2 },
 { id: '03', name: 'Clinical NLP & LLMs', tag: 'NLP + LLMs', icon: 'quote', color: 'coral', description: 'How machines read, structure and generate health language — and why clarity, provenance and oversight have to stay visible.', examples: 'Clinical notes · retrieval · patient communication', note: 1 },
 { id: '04', name: 'Medical Imaging AI', tag: 'COMPUTER VISION', icon: 'eye', color: 'violet', description: 'Reading images, slides and video with AI. The interesting question is not only what a model sees, but how care changes around it.', examples: 'Radiology · pathology · ophthalmology', note: 3 },
 { id: '05', name: 'Precision Medicine', tag: 'MULTIMODAL AI', icon: 'helix', color: 'gold', description: 'Connecting genomics, biomarkers, images and records to move from population averages toward more specific questions.', examples: 'Genomics · drug discovery · tailored treatment', note: 4 },
 { id: '06', name: 'Remote Patient Monitoring', tag: 'SENSING + SIGNALS', icon: 'wave', color: 'ink-card', description: 'What changes when health signals continue beyond the clinic — and when monitoring becomes part of daily life?', examples: 'Wearables · remote monitoring · population health', note: 5 },
];
function FieldIcon({ kind }: { kind: string }) { return <Emblem variant={['pulse','loop','quote','eye','helix','wave'].indexOf(kind)+1} className="field-icon"/>; }
export default function Home() {
 const [fieldArticle, setFieldArticle] = useState<number | null>(null);
 const [audience, setAudience] = useState(0); const [activeField, setActiveField] = useState(0); const [contact, setContact] = useState(false); const [menu, setMenu] = useState(false); const [feedback, setFeedback] = useState(''); const [scrolled, setScrolled] = useState(false);
 useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 30); onScroll(); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll); }, []);
 function explore(_field?: string) { document.getElementById('explore')?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' }); }
 return <FluentProvider theme={theme} className="site"><a className="skip" href="#main">Skip to content</a>
 <header className={'masthead ' + (scrolled ? 'compact' : '')}><a className="identity-lockup" href="#" aria-label="think.anas home"><Wordmark /><span className="identity-caption">ARTIFICIAL INTELLIGENCE · HEALTHCARE</span></a><nav id="main-navigation" className={menu ? 'navigation expanded' : 'navigation'} aria-label="Main navigation"><a href="#explore" onClick={() => setMenu(false)}><span>AI Applications</span></a><a href="#perspectives" onClick={() => setMenu(false)}><span>Use Cases</span></a><a href="#about" onClick={() => setMenu(false)}><span>About Anas</span></a></nav><button className="nav-contact" aria-label="Start a conversation" onClick={() => setContact(true)}><span className="contact-label">Contact</span><VectorMark /></button><Button className="menu-button" aria-controls="main-navigation" aria-expanded={menu} aria-label={menu ? 'Close navigation' : 'Open navigation'} onClick={() => setMenu(!menu)}>{menu ? 'Close' : 'Menu'}</Button></header>
 <main id="main"><section className="hero"><div className="hero-topline"><p className="micro">INDEPENDENT THINKING AT THE INTERSECTION OF AI & HEALTH</p></div><div className="hero-composition"><div className="hero-type"><h1>Stay human.<br/><span>Think further.</span></h1><div className="hero-intro"><span className="tiny-cross" aria-hidden="true">+</span><p>Explore clinical AI, language models and automation.<br className="desktop-break"/> Understand the applications, limits and human decisions.</p></div><a className="button-lime" href="#explore">Explore AI applications <VectorMark/></a></div><figure className="hero-art"><LivingSculpture/></figure></div><div className="hero-bottom"><span>THINK.ANAS — A PERSONAL EXPLORATION</span><a href="#manifesto">Scroll to discover <span>↓</span></a></div></section>
 <div className="ribbon" aria-label="Human questions, artificial intelligence, real perspective"><span>HUMAN QUESTIONS</span><TMark/><span>ARTIFICIAL INTELLIGENCE</span><TMark/><span>REAL PERSPECTIVE</span><TMark/></div>
 <section id="manifesto" className="manifesto light-section"><div className="section-label"><span className="micro">THE STARTING POINT</span><span className="micro">TECHNOLOGY · EVIDENCE · CARE</span></div><div className="manifesto-grid"><TMark className="manifesto-emblem"/><div><h2>More than what AI <i>can</i> do.<br/>What should it <i>mean</i> for us?</h2><div className="manifesto-bottom"><p>Health is human. Technology is a tool. This is a space to explore the messy, fascinating territory in between — with curiosity, context and an open mind.</p><a className="underlined" href="#about">The person behind the questions <VectorMark/></a></div></div></div></section>
 <section id="explore" className="index-section light-section"><div className="section-label"><span className="micro">AI APPLICATIONS</span><span className="micro">METHODS. APPLICATIONS. LIMITATIONS.</span></div><div className="index-heading"><h2>AI in<br/><i>healthcare.</i></h2><div><p>Understand the methods.<br/>Evaluate their applications.</p><span className="sample-label">TECHNICAL OVERVIEWS</span></div></div><div className="field-map" aria-label="Six healthcare AI application domains">{fieldMap.map((field,index) => <article className={'field-card ' + field.color + (activeField === index ? ' active' : '')} key={field.id} onMouseEnter={() => setActiveField(index)} onFocus={() => setActiveField(index)}><div className="field-mark"><FieldIcon kind={field.icon}/></div><div className="field-base"><span className="field-tag">{field.tag}</span><h3>{field.name}</h3></div><div className="field-reveal"><p>{field.description}</p><span>{field.examples}</span></div><button className="organ-read" onClick={() => setFieldArticle(index)} aria-label={'Explore applications: ' + field.name}>Explore applications <VectorMark/></button></article>)}</div><p className="collection-caption">An editorial selection of six application domains. Methods and use cases can overlap.</p></section>
 <section id="perspectives" className="perspectives dark-section"><div className="section-label"><span className="micro">USE CASES</span><span className="micro">ILLUSTRATIVE WORKFLOWS</span></div><div className="perspective-heading"><h2>Clinical AI.<br/><span>Practical applications.</span></h2><p>Understand the workflow.<br/>Identify the human checkpoint.</p></div><div className="perspective-grid"><div className="perspective-tabs" role="group" aria-label="Choose a clinical application">{['Clinical documentation','Imaging review','Clinical risk prediction','Remote monitoring'].map((a,i) => <button key={a} aria-pressed={audience === i} onClick={() => setAudience(i)} className={audience === i ? 'selected' : ''}>{a}<VectorMark/></button>)}</div><div className="perspective-panel" aria-live="polite"><span className="micro">APPLICATION WORKFLOW</span><h3>{['From conversation to clinical note.','From image to review priority.','From records to a risk estimate.','From sensor data to clinical review.'][audience]}</h3><p>{['Audio → transcription → draft note → clinician review. A documentation workflow should make omissions and corrections easy to identify before a note is saved.','Medical image → model output → specialist review. An illustrative triage workflow: the model suggests a priority, while the clinician interprets the examination.','Patient records → risk estimate → clinician assessment. Performance, calibration and the response to an alert need evaluation in the intended setting.','Sensor data → signal analysis → alert → care-team review. Define who receives an alert, what action is possible and how false alarms are handled.'][audience]}</p><button className="underlined" onClick={() => setFieldArticle([2,3,0,5][audience])}>Explore this application <VectorMark/></button></div></div></section>
 <section id="about" className="about-section light-section"><div className="section-label"><span className="micro">ABOUT ANAS</span><span className="micro">YES, THERE’S A PERSON BEHIND THIS.</span></div><div className="about-grid"><div className="portrait-composition"><figure><img src="/anas.png" alt="Anas, the person behind think.anas"/><figcaption>ANAS <span>ALWAYS A WORK IN PROGRESS.</span></figcaption></figure><span className="portrait-sticker">Human.<br/>Still learning.</span></div><div className="about-copy"><p className="micro">CREATOR OF @THINK.ANAS</p><h2>Hi, I’m Anas.<br/><i>Curiosity led me here.</i></h2><p>I’m exploring what happens when artificial intelligence meets human health. The possibilities, the unanswered questions, and the people at the centre of it all.</p><p>think.anas is where I connect the dots. A personal space for learning in public, thinking a little deeper and finding people to explore with.</p><div className="editorial-margin"><span className="micro">QUESTIONS IN THE MARGIN</span><p className="hand-note">What am I missing?</p><p>Who benefits? What is the evidence? What would change my mind?</p><a className="underlined" href="https://www.who.int/health-topics/artificial-intelligence" target="_blank" rel="noreferrer">Explore the WHO AI & health resources <VectorMark/></a></div><a className="underlined" href="https://www.instagram.com/think.anas/" target="_blank" rel="noreferrer">Meet me on Instagram <VectorMark/></a></div></div><div className="principles"><span className="micro">THREE THINGS I COME BACK TO</span>{[['01','Ask something useful.'],['02','Follow the evidence.'],['03','Remember the person.']].map(([n,t]) => <div key={n}><h3>{t}</h3></div>)}</div></section>
 <section className="collaboration-section"><div className="section-label"><span className="micro">CONTACT</span><span className="micro">OPEN TO IDEAS. OPEN TO PEOPLE.</span></div><div className="collaboration-heading"><h2>Good ideas<br/>need <i>company.</i></h2><button className="giant-arrow" aria-label="Bring an idea" onClick={() => setContact(true)}><VectorMark /></button></div><div className="collaboration-bottom"><p>A shared question. A useful resource.<br/>An experiment worth trying.<br/>Let’s see where a conversation takes us.</p><div className="collaboration-types"><span>EXPLORE</span><span>EXPLAIN</span><span>BUILD</span><span>BRING PEOPLE TOGETHER</span></div><button className="button-ink" onClick={() => setContact(true)}>Bring an idea <VectorMark /></button></div></section>
 <footer><div className="footer-top"><a href="#" aria-label="Back to top"><Wordmark /></a><p>Stay human. Think further.</p><a href="https://www.instagram.com/think.anas/" target="_blank" rel="noreferrer">Instagram <VectorMark/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} THINK.ANAS</span><span>AI × HEALTH × HUMAN CURIOSITY</span><a href="#">BACK TO TOP ↑</a></div></footer></main>
 <Dialog open={fieldArticle !== null} onOpenChange={(_,d) => !d.open && setFieldArticle(null)}><DialogSurface className="research-layer"><DialogBody>{fieldArticle !== null && <><aside className={'research-spine ' + fieldMap[fieldArticle].color}><FieldIcon kind={fieldMap[fieldArticle].icon}/><span>APPLICATION BRIEF</span></aside><div className="research-paper"><DialogTitle>{fieldMap[fieldArticle].name}</DialogTitle><DialogContent><p className="dialog-meta">{fieldMap[fieldArticle].tag} / EDITORIAL EXPLORATION</p><section><span className="micro">TECHNICAL OVERVIEW</span><p>{fieldMap[fieldArticle].description}</p></section><section><span className="micro">APPLICATION EXAMPLES</span><p>{fieldMap[fieldArticle].examples}</p></section><section><span className="micro">IMPLEMENTATION QUESTION</span><p>{['Who checks a prediction, and what changes when they disagree?','Does this remove work, or simply move it to another person?','Can the reader trace a generated statement back to its source?','What happens when an image falls outside the model’s experience?','Whose biology is represented in the data, and whose is missing?','Who responds to a signal, and when is monitoring no longer helpful?'][fieldArticle]}</p></section><p className="hand-note">A starting point for inquiry. Keep the questions open.</p></DialogContent><DialogActions><Button appearance="primary" onClick={() => setFieldArticle(null)}>Close overview</Button></DialogActions></div></>}</DialogBody></DialogSurface></Dialog>
 <Dialog open={contact} onOpenChange={(_,d) => { setContact(d.open); setFeedback(''); }}><DialogSurface className="contact-dialog"><DialogBody><DialogTitle>Every good idea starts somewhere.</DialogTitle><DialogContent><p>Prepare a short introduction, then share it with @think.anas on Instagram. This form creates a download; it does not send a message.</p><form id="idea-form" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); const text = Array.from(data.entries()).map(([k,v]) => `${k}: ${v}`).join('\n\n'); const url = URL.createObjectURL(new Blob([text], { type: 'text/plain' })); const a = document.createElement('a'); a.href = url; a.download = 'an-idea-for-think-anas.txt'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setFeedback('Your introduction is ready to download. Share it with @think.anas to start the conversation.'); }}><div className="form-pair"><Field label="Your name" required><Input name="Name" required /></Field><Field label="Email or Instagram" required><Input name="Contact" required /></Field></div><Field label="What brings you here?"><Select name="Collaboration"><option>A question to explore</option><option>A resource to create</option><option>An experiment to build</option><option>A podcast or workshop</option><option>Something unexpected</option></Select></Field><Field label="Tell me the idea" required><Textarea name="Idea" required rows={4} /></Field><Field label="Timing, if you have it"><Input name="Timing" /></Field></form><p role="status">{feedback}</p><a className="underlined" href="https://www.instagram.com/think.anas/" target="_blank" rel="noreferrer">Open @think.anas <VectorMark/></a></DialogContent><DialogActions><Button onClick={() => setContact(false)}>Close</Button><Button appearance="primary" form="idea-form" type="submit">Download introduction <VectorMark/></Button></DialogActions></DialogBody></DialogSurface></Dialog>
 </FluentProvider>;
}
